name: package-desktop

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  package-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Package Linux app
        run: npm run package:linux

      - name: Upload Linux app artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: DexuX-linux-${{ github.sha }}
          path: |
            release/*.AppImage
            release/*.blockmap
          if-no-files-found: error

      - name: Upload Linux release assets
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            release/*.AppImage
            release/*.blockmap

  package-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Package Windows app
        run: npm run package:win

      - name: Upload Windows app artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: DexuX-windows-${{ github.sha }}
          path: |
            release/*.exe
            release/latest*.yml
          if-no-files-found: error

      - name: Upload Windows release assets
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            release/*.exe
            release/latest*.yml
